### ISSUE TITLE
fulfilment rather than fulfillment

### ISSUE THREAD

**Issue by vorlon77** [rzach/ucalgary-memoir-thesis#1]
The guidelines at https://grad.ucalgary.ca/sites/default/files/teams/3/Thesis%20Guidelines_May%202020.pdf show that FULFILMENT should be used on the title page rather than FULFILLMENT.  Yes, they do push back a little bit on this.

**Comment by rzach** [comment]
OMG.
Fixed it; also a better solution to uppercasing the month. (In my defence/defense I copied the title page text from the old templates). Let me know if you have more suggestions.

**Comment by rzach** [comment]
FTR this is now updated in CTAN as well
